/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void VadymWork() {
        System.out.println("Vadym's work goes here");
    }

    public static void KrisWork() {
        System.out.println("Kris's work goes here");
    }

    public static void PatrickWork() {
        System.out.println("Patrick's work goes here");
    }

    public static void GregWork() {
        System.out.println("Greg's work goes here");
    }

    public static void main(String[] args) {
        VadymWork();
        KrisWork();
        PatrickWork();
        GregWork();
        Decklist.main(args);
    }
}